# Generated by Django 4.2.7 on 2025-10-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_founditem_returned_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='returned_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='found_confirmed_at',
        ),
    ]
